In [1]:
!pip install numpy==2.2.0
!pip install pandas==2.2.3
!pip install scikit-learn==1.6.0
!pip install matplotlib==3.9.3

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.1/16.1 MB 142.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 148.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 136.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.2/35.2 MB 222.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 101.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 131.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 88.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 144.1 MB/s eta 0:00:00


In [3]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [9]:
from sklearn import datasets

iris =  datasets.load_iris()
iris_data= iris.data
iris_data = pd.DataFrame(iris_data,columns=iris.feature_names) 
iris_data['class']= iris.target
iris_data.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),class
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


In [29]:
x= iris_data.iloc[:,[0,1,2,3]]
y= iris_data.iloc[:,[4]]

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [30]:
type(y_train)

pandas.core.frame.DataFrame

In [39]:
model = KNeighborsClassifier() 
model.fit(x_train, y_train.values.ravel())
y_pred = model.predict(x_test) 
print("Accuracy Score: %.2f"%accuracy_score(y_test,y_pred))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

Accuracy Score: 1.00
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


In [41]:
model = RandomForestClassifier() 
model.fit(x_train, y_train.values.ravel())
y_pred = model.predict(x_test) 
print("Accuracy Score: %.2f"%accuracy_score(y_test,y_pred))

from sklearn.metrics import classification_report

print( classification_report(y_test,y_pred))

Accuracy Score: 1.00
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [36]:
model = SVC() 
model.fit(x_train, y_train.values.ravel())
y_pred = model.predict(x_test) 
print("Accuracy Score: %.2f"%accuracy_score(y_test,y_pred))

Accuracy Score: 1.00


In [37]:
model = LogisticRegression() 
model.fit(x_train, y_train.values.ravel())
y_pred = model.predict(x_test) 
print("Accuracy Score: %.2f"%accuracy_score(y_test,y_pred))

Accuracy Score: 1.00
